# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build the HMDP (3 levels with shared linking) using the C++ binary writer.
#'
#' The MDP specified at level 3 is generated for each tillage operation for a dummy state at the first stage at level 2.
#'
#' @param filePrefix Prefix used by the binary files storing the MDP model.
#' @param paramModel parameters a list created using \code{\link{setParameters}}.
#'
#' @return Build log (character).
#' @export
BuildHMDP <- function(filePrefix, paramModel) {
    .Call('hmdpTillage_BuildHMDP', PACKAGE = 'hmdpTillage', filePrefix, paramModel)
}

